// Generated by gencpp from file control_380/Motor.msg
// DO NOT EDIT!


#ifndef CONTROL_380_MESSAGE_MOTOR_H
#define CONTROL_380_MESSAGE_MOTOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace control_380
{
template <class ContainerAllocator>
struct Motor_
{
  typedef Motor_<ContainerAllocator> Type;

  Motor_()
    : angles()  {
      angles.assign(0.0);
  }
  Motor_(const ContainerAllocator& _alloc)
    : angles()  {
  (void)_alloc;
      angles.assign(0.0);
  }



   typedef boost::array<float, 5>  _angles_type;
  _angles_type angles;





  typedef boost::shared_ptr< ::control_380::Motor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_380::Motor_<ContainerAllocator> const> ConstPtr;

}; // struct Motor_

typedef ::control_380::Motor_<std::allocator<void> > Motor;

typedef boost::shared_ptr< ::control_380::Motor > MotorPtr;
typedef boost::shared_ptr< ::control_380::Motor const> MotorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_380::Motor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_380::Motor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::control_380::Motor_<ContainerAllocator1> & lhs, const ::control_380::Motor_<ContainerAllocator2> & rhs)
{
  return lhs.angles == rhs.angles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::control_380::Motor_<ContainerAllocator1> & lhs, const ::control_380::Motor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace control_380

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::control_380::Motor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_380::Motor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_380::Motor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_380::Motor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_380::Motor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_380::Motor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_380::Motor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da37f2396c41d2822a851fce98ae8df1";
  }

  static const char* value(const ::control_380::Motor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda37f2396c41d282ULL;
  static const uint64_t static_value2 = 0x2a851fce98ae8df1ULL;
};

template<class ContainerAllocator>
struct DataType< ::control_380::Motor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_380/Motor";
  }

  static const char* value(const ::control_380::Motor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_380::Motor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[5] angles\n"
"\n"
;
  }

  static const char* value(const ::control_380::Motor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_380::Motor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Motor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_380::Motor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_380::Motor_<ContainerAllocator>& v)
  {
    s << indent << "angles[]" << std::endl;
    for (size_t i = 0; i < v.angles.size(); ++i)
    {
      s << indent << "  angles[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.angles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_380_MESSAGE_MOTOR_H
